# Site settings
title: xmlet/HtmlFlow
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "HtmlFlow web site"
url: "https://xmlet.github.io/HtmlFlow/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
